- app/Extensions/GraphQL.php
This pr lets a query to expose the user email and id when we want it.
> Wooless 1584 make rewards accessible on frontend jameshwart lopez

- app/Settings/ProductPageSettings.php
This pr adds a new filed for icon, title and save those info to typesense. 
related pr in the frontend 
https://github.com/blaze-commerce/blaze-commerce-front-end-site-build-next.js/pull/73
> Wooless 1567 plugin make privacy policy and returns title configurable jameshwart lopez

- app/Extensions/GraphQL.php
- app/Features/Authentication.php
- this pr will let graphql api to have username and name of the user who logs in when you request it.
> Wooless 1625 frontend login not working jameshwart lopez

- app/Collections/Product.php
Saving backorder data to typesense
> feat: add backorder data to typesense

- app/BlazeWooless.php
- app/Settings/SynonymSettings.php
- app/TypesenseClient.php
- assets/css/blaze-wooless.css
- blaze-wooless.php
- views/synonym-management.php
> feat: add synonym setting in plugin setting and sync with typenses

- app/BlazeWooless.php
- app/Features/Review.php
- app/Settings/ProductPageSettings.php
- blaze-wooless.php
in blaze commerce > product page, i've added a new option to exclude the review from the product tabs
> Wooless 2304 product page let customers speak for us ridwan arifandi

- CHANGELOG.md
- app/Features/LoadCartFromSession.php
- app/Settings/GeneralSettings.php
- blaze-wooless.php
> Wooless 2874 bc plugin update ridwan arifandi

- app/Woocommerce.php
feat: update the main product price from its variables
> Wooless 2776 sorting the price from low to highhigh to low doesnt work correctly ridwan arifandi

- app/Extensions/WoocommerceGiftCards.php
- app/Woocommerce.php
fix issue with gift card price if allowed custom amount
> fix: gift card min price if allowed custom amount

- app/BlazeWooless.php
> fix: wp page cors error

- app/Features/Cli.php
Add a new CLI parameter to sync only non-variant products (simple, bundle, etc.) This allows for more targeted syncing when only simple products need to be updated without processing variable products and their variations.
> feat: Add --nonvariants parameter to product sync CLI command

- .augmentignore
Adds a comprehensive `.augmentignore` file to optimize Augment Code's context engine for this WordPress plugin repository.
- **WordPress-specific ignores**: Core files, uploads, cache, and plugin directories
- **Build and dependency ignores**: node_modules, vendor, build outputs
- **Media file ignores**: Large images, videos, and other binary files
- **Database file ignores**: .sql files and database dumps
- **System file ignores**: OS-generated files, IDE directories
- **Whitelist important files**: Configuration files, package.json, composer.json, etc.
- Improves Augment Code context retrieval performance
- Reduces noise from irrelevant files
- Focuses on actual plugin development code
- Follows BlazeCommerce development best practices
- `.augmentignore` - New comprehensive ignore file …
> Add comprehensive .augmentignore file

- .augment-guidelines
🚨 BREAKING CHANGE: Mandatory Documentation Requirements
This PR introduces **mandatory comprehensive documentation requirements** for all code changes in the BlazeCommerce WordPress Plugin project, following the same standards established in blazecommerce-child repository.
Implements a documentation-first development workflow where **all code changes must include corresponding documentation updates**. No exceptions.
- **MANDATORY Documentation Requirements**: All changes must include .md file updates
- **Documentation-First Workflow**: Code without docs will be rejected
- **Comprehensive Documentation Structure**: Defined required .md files in `/docs/`
- **Enhanced Commit Guidelines**: Documentation commits now mandatory
- **Pre-Commit Requirements**: Documentation completeness checks
``` …
```
> feat(docs): Mandate comprehensive .md documentation for all changes

- .github/workflows/claude-code-review.yml
The GitHub Actions workflow for Claude Code Review (`.github/workflows/claude-code-review.yml`) has been failing intermittently with **API Error 529 ("overloaded_error": "Overloaded")** from the Anthropic Claude API. This error indicates that the external service is temporarily overloaded, causing the entire workflow to fail immediately without any retry mechanism.
**Impact:**
- Pull requests are not receiving automated code reviews when the API is under high load
- Developers need to manually re-trigger workflows multiple times
- No graceful handling of temporary API unavailability
- Workflow failures create noise and reduce confidence in the CI/CD pipeline
**Example failure:** https://github.com/blaze-commerce/blazecommerce-wp-plugin/actions/runs/16197341231/job/45727170551
Implemented …
> feat: add retry logic with exponential backoff for Claude Code Review workflow

- .github/workflows/release.yml
The GitHub Actions release workflow was failing due to a YAML syntax error on **line 197** in `.github/workflows/release.yml`. This was identified in GitHub Actions run [#16224317395](https://github.com/blaze-commerce/blazecommerce-wp-plugin/actions/runs/16224317395/workflow).
**Error Message:**
```
Invalid workflow file: You have an error in your yaml syntax on line 197
```
The issue was caused by **improper multi-line string handling** within shell scripts in the YAML file:
1. **Heredoc syntax** (`cat << EOF`) within YAML confused the YAML parser
2. **Unescaped multi-line strings** spanning multiple lines without proper YAML formatting
3. **Variable substitution** within unescaped multi-line strings created syntax conflicts
Replaced problematic multi-line string assignments with **bash …
> Fix YAML syntax error in release workflow

- CHANGELOG.md
- blaze-wooless.php
- blocks/package.json
- lib/blaze-wooless-functions.php
- package-lock.json
- package.json
This Pull Request is designed to test and verify the functionality of our automated version bumping (`auto-version.yml`) and release creation (`release.yml`) workflows.
- **Added**: `blaze_wooless_test_version_bump_feature()` function in `lib/blaze-wooless-functions.php`
- **Purpose**: Provides a simple test utility that triggers the automated version bump workflow
- **Impact**: Safe addition that doesn't affect existing plugin functionality
**Trigger Conditions:**
- ✅ Branch: `feature/test-auto-versioning` (matches `feature/**` pattern)
- ✅ File Changed: `lib/blaze-wooless-functions.php` (NOT in paths-ignore)
- ✅ Commit Message: `feat: add test feature for version bump` (conventional commit format)
**Expected Version Bump:**
- **Current Version**: `1.8.0`
- **Bump Type**: `MINOR` (due to …
> feat: test automated version bumping and release workflows

- .github/workflows/auto-version.yml
The automatic version bump system was producing **unexpected minor version bumps** instead of patch bumps due to a version synchronization mismatch between package.json and git tags.
- **Expected**: `1.11.0` → `1.11.1` (patch bump for `fix:` commit)
- **Actual**: `1.11.0` → `1.12.0` (minor bump)
- **Root Cause**: Workflow analyzed 250+ commits since outdated tag `1.4.7` instead of recent changes
- Added new workflow step to detect mismatches between `package.json` version and git tags
- Provides clear warnings when version inconsistencies are detected
- Outputs validation results for use in subsequent steps
- **Before**: Always analyzed commits since last git tag (potentially hundreds of commits)
- **After**: Uses limited commit analysis (last 10 commits) when version mismatch is detected …
> fix(versioning): prevent unexpected version increments in auto-version workflow

- .github/workflows/auto-version.yml
- .github/workflows/release.yml
- scripts/README.md
- scripts/check-file-changes.sh
- scripts/get-ignore-patterns.sh
- tests/test-file-detection.sh
This PR enhances both the auto-version and release workflows to intelligently skip processing when only ignored files (documentation, CI/CD configs, tooling) are changed, eliminating unnecessary version bumps and releases while maintaining successful workflow completion.
- **Removed `paths-ignore`**: Workflow now always runs instead of being skipped entirely
- **Intelligent File Detection**: Added step to analyze changed files in each push
- **Skip Logic**: Workflow skips version bumping when only ignored files are modified
- **Conditional Processing**: All version-related steps now conditional based on file analysis
- **Success Completion**: Workflow completes successfully in all scenarios (no more failed status)
- **Clear Feedback**: Comprehensive summary explains what happened and why …
> Enhancement: Improve GitHub Workflow Behavior for Ignored Files

- scripts/check-file-changes.sh
- scripts/get-ignore-patterns.sh
- scripts/test-version-bump-logic.sh
The auto-version workflow was incorrectly skipping version bumps for core plugin functionality changes. Specifically, [workflow run 16240123475](https://github.com/blaze-commerce/blazecommerce-wp-plugin/actions/runs/16240123475/job/45855395678) failed to trigger a version bump despite changes to critical plugin files:
- `app/BlazeWooless.php` - Core plugin file
- `app/Features/PluginIntegrationUrlManager.php` - New feature implementation
- `lib/blaze-wooless-functions.php` - Core plugin functions
- `test/test-plugin-integration-url-manager.php` - Test file (should be ignored)
The issue was caused by **two critical bugs**:
- The file detection script had a bug in processing stdin input
- `set -euo pipefail` was causing the script to exit after processing the first file
- The script was …
> fix: resolve auto-version workflow incorrectly skipping version bumps

- app/Settings/GeneralSettings.php
- docs/security/credential-management-guidelines.md
- docs/security/klaviyo-api-key-security-fix.md
- docs/security/security-audit-summary.md
- lib/blaze-wooless-functions.php
- lib/setting-helper.php
- test/test-klaviyo-security-fix.php
**SEVERITY**: HIGH  
**TYPE**: Hardcoded Credentials  
**IMPACT**: API key exposure in version control  
This PR addresses a critical security vulnerability where the Klaviyo API key was hardcoded in the source code, potentially exposing it to unauthorized access.
- **Location**: `lib/blaze-wooless-functions.php` (lines 114 & 126)
- **Vulnerability**: Hardcoded Klaviyo API key `"W7A7kP"`
- **Risk Level**: HIGH
- **Exposure**: Credentials visible in version control and public repositories
- **Functions Affected**: `klaviyo_script()` and `is_klaviyo_connected()`
- ❌ **Confidentiality**: HIGH - API key exposed to repository access
- ❌ **Integrity**: MEDIUM - Potential unauthorized API usage
- ❌ **Availability**: LOW - Risk of API quota exhaustion
- ❌ **Compliance**: HIGH - Violates security …
> fix(security): remove hardcoded Klaviyo API key

- .github/workflows/claude-pr-review-secure.yml
- docs/development/claude-ai-bot/SECURITY_ANALYSIS_SIMPLE_WORKFLOW.md
- docs/development/claude-ai-bot/SECURITY_GATES.md
This PR addresses a **critical security vulnerability** where the simplified Claude AI Review workflow (`claude-pr-review-simple.yml`) was **automatically approving ALL PRs without any security validation**. This created a severe security risk by allowing potentially vulnerable code to be merged without proper review.
- **Issue**: Simple workflow approved every PR regardless of security issues
- **Risk Level**: 🔴 **CRITICAL**
- **Impact**: Security vulnerabilities, SQL injection, XSS, and other critical issues were auto-approved
- **Issue**: No validation of 🔴 REQUIRED recommendations from Claude AI review
- **Risk Level**: 🔴 **CRITICAL** 
- **Impact**: Critical security issues identified by Claude AI were ignored
- **Issue**: No scanning for WordPress-specific security vulnerabilities
- …
> SECURITY: Fix - Restore security gates in Claude AI Review workflow

- .github/workflows/auto-version.yml
- .github/workflows/release.yml
- docs/development/automation.md
- docs/development/version-workflow-fixes.md
This PR fixes critical issues in the auto-versioning and release workflows that were causing consistent failures and preventing successful version management.
1. **Git Configuration Issues**: Using incorrect email format causing commit failures
2. **Token Permission Issues**: Missing `actions: read` permission preventing workflow access
3. **Commit Process Failures**: No error handling or debugging for failed commits
4. **Token Handling**: Hard-coded token reference without fallback logic
1. **Missing Permissions**: Jobs lacked proper permissions for GitHub API access
2. **Release Creation Failures**: No verification that releases were actually created
3. **Token Issues**: No fallback to default GitHub token
4. **Error Detection**: Poor error reporting for troubleshooting
```yaml
- name: …
```
> fix: repair auto-version and release workflows

- .github/workflows/claude-pr-review.yml
- docs/development/claude-workflow-sequence.md
This PR fixes the critical issue preventing Claude AI review workflows from triggering on legitimate workflow improvement PRs (like PR #332) due to overly broad skip logic.
The main Claude PR review workflow was incorrectly skipping important workflow improvement PRs due to this problematic logic:
```javascript
// ❌ PROBLEMATIC LOGIC (Before Fix)
const isWorkflowFix = commitMessage.includes('workflow') ||
commitMessage.includes('fix:') ||  // TOO BROAD!
commitMessage.includes('claude') ||
files.some(file => file.filename.startsWith('.github/workflows/'));
```
**Problems**:
- `commitMessage.includes('fix:')` matched **ANY** fix commit, not just workflow fixes
- No distinction between minor maintenance and major workflow improvements
- Blocked legitimate workflow improvement PRs that needed …
> fix: improve Claude PR review workflow trigger conditions

- .github/workflows/claude-pr-review.yml
This PR fixes the critical syntax error in the main Claude PR review workflow that was preventing it from running and causing PRs to only receive auto-approval without detailed review comments.
The main Claude PR review workflow was **consistently failing** immediately without running any jobs, indicating a syntax error in the workflow file.
**Evidence**:
- Workflow runs showed `conclusion: failure` with `total_count: 0` jobs
- No jobs executed = YAML/JavaScript syntax error
- GitHub Actions couldn't parse the workflow file
1. **JavaScript `!` Character Issue**:
```javascript
// ❌ PROBLEMATIC (Caused syntax error)
!file.filename.includes('claude-pr-review')
// ✅ FIXED
file.filename.indexOf('claude-pr-review') === -1
```
2. **Multi-line YAML Condition**:
```yaml
if: |
github.event_name == …
```
> fix: repair Claude PR review workflow syntax error

- .github/workflows/auto-version.yml
- .github/workflows/claude-pr-review-secure.yml
- .github/workflows/release.yml
- docs/development/changelog-path-fix-summary.md
- docs/development/changelog-path-fix.md
- docs/development/performance-optimizations.md
- docs/development/pr-328-implementation-checklist.md
- docs/development/pr-328-implementation-summary.md
- docs/security/security-enhancements.md
- scripts/config.js
- scripts/update-changelog.js
- test/test-changelog-path-fix.js
This PR fixes the discrepancy between automated changelog generation and project documentation organization guidelines. The `scripts/update-changelog.js` script now correctly updates the changelog at `docs/reference/changelog.md` instead of creating/updating `CHANGELOG.md` in the root directory.
- **`scripts/update-changelog.js`**: Updated to use `docs/reference/changelog.md` path
- Added `CHANGELOG_PATH` constant for centralized path configuration
- Implemented `ensureChangelogDirectory()` for automatic directory creation
- Added frontmatter preservation with `extractFrontmatter()` and `createDefaultFrontmatter()`
- Enhanced error handling and logging throughout
- **`.github/workflows/release.yml`**: Updated changelog path references
- **`.github/workflows/auto-version.yml`**: Updated …
> fix: align changelog path with documentation standards

- .github/workflows/claude-pr-review.yml
The main Claude PR review workflow (`claude-pr-review.yml`) has been experiencing **consistent startup failures**, preventing automatic code reviews while `@claude` mentions work perfectly.
**Evidence:**
- ❌ Automatic workflow: STARTUP_FAILURE (runs #248-255)
- ✅ Manual `@claude` mentions: Working perfectly
- 🔍 **Root Cause**: Startup failures occur BEFORE the Anthropic action even runs
**Both workflows use the same technology:**
- Same `anthropics/claude-code-action@beta`
- Same `${{ secrets.ANTHROPIC_API_KEY }}`
- Same authentication method
**The difference:**
- ✅ **Manual workflow**: 60 lines, simple implementation
- ❌ **Automatic workflow**: 1,980 lines, complex preprocessing
**Simplified the workflow from 1,980 lines to 338 lines (83% reduction)** while preserving all essential …
> fix: simplify Claude PR review workflow to resolve startup failures

- .github/workflows/claude-pr-review.yml
- .github/workflows/debug-pr-triggers.yml
This PR is created to test and debug the Claude AI PR Review automatic triggering issue identified in PR #337.
1. **Added debug logging** to `claude-pr-review.yml` to identify trigger issues
2. **Fixed concurrency setting** - changed `cancel-in-progress` to `false`
3. **Created debug workflow** `debug-pr-triggers.yml` to test PR event triggering
When this PR is created, the following should happen automatically:
1. ✅ `DEBUG: PR Trigger Test` workflow should run immediately
2. ✅ `BlazeCommerce Claude AI Review Bot` should trigger automatically
3. ✅ Debug logs should show the workflow execution details
The issue appears to be that workflows only trigger from the default branch (main), not from feature branches. This PR tests the fix by updating the main branch workflows.
---
**This is a …
> DEBUG: Test Claude AI PR Review Automatic Triggering

- README.md
This PR tests the automatic version bump workflow with a minimal documentation change to verify the system correctly identifies and processes conventional commits.
- **Current Version**: 1.12.0 (package.json)
- **Expected New Version**: 1.12.1 (patch increment)
- **Commit Format**: `fix: update documentation comment`
- **Change Made**: Added a small HTML comment to README.md
When this PR is merged to main:
1. **Auto-version.yml workflow** should trigger on push to main
2. **Commit Analysis**: Should detect `fix:` prefix and determine patch bump needed
3. **Version Updates**: Should automatically update:
- `package.json` version: 1.12.0 → 1.12.1
- `blaze-wooless.php` version header
- `CHANGELOG.md` with new version entry
4. **Automatic Commit**: Should create commit with format …
> test: verify automatic version bump system with patch increment

- README.md
This PR tests the newly fixed automatic version bump system to verify that the issues resolved in PR #344 are working correctly.
- **Fixes Applied**: PR #344 - fix: resolve automatic version bump system failures
- **Original Issue**: Version bump system failed to update versions despite successful workflow runs
- **Root Cause**: Tag conflicts, incorrect bump type detection, and missing file synchronization
- **Current Version**: 1.12.0 (package.json, blaze-wooless.php)
- **README.md Version**: 1.11.0 (outdated - should be updated by this test)
- **Commit Type**: `fix:` (should trigger patch bump)
- **Expected New Version**: 1.12.1
- **File Modified**: README.md
- **Change**: Added documentation comment about dependency requirements
- **Commit Message**: `fix: update documentation comment …
> test: validate fixed automatic version bump system with patch increment

- package.json
This PR contains a change to `package.json` which is **EXPLICITLY LISTED** as a critical file in the file change analyzer. This is the definitive test to determine if the version bump workflow is functioning correctly.
- ✅ **Explicitly listed in critical patterns**: `['blaze-wooless.php', 'package.json', 'composer.json']`
- ✅ **Root level configuration file** - NEVER ignored
- ✅ **Contains version information** - Core to version management
```json
// ADDED
"test:version-bump": "echo 'Testing version bump workflow'",
```
**Purpose**: Added a test script to validate the version bump workflow functionality.
According to the analyzer code:
```javascript
const criticalPatterns = ['blaze-wooless.php', 'package.json', 'composer.json'];
if (criticalPatterns.some(pattern => …
```
> fix: add test script for version bump workflow validation

- README.md
- blaze-wooless.php
- blocks/package.json
- package-lock.json
- package.json
- version-sync-commands.sh
This PR resolves version inconsistencies by updating all version references in the codebase to match the latest git tag v1.14.0. All version files are now properly synchronized.
A comprehensive version audit revealed a critical inconsistency:
- **Git tag**: `v1.14.0` (latest)
- **All version files**: `1.12.0` (outdated)
This discrepancy could cause deployment issues, plugin conflicts, and user confusion.
Used the built-in version update script to synchronize all version files:
```bash
node scripts/update-version.js 1.14.0 --force --verbose
```
- ✅ `package.json`: `1.12.0` → `1.14.0`
- ✅ `blaze-wooless.php` (Plugin Header): `1.12.0` → `1.14.0`
- ✅ `blaze-wooless.php` (PHP Constant): `1.12.0` → `1.14.0`
- ✅ `blocks/package.json`: `1.12.0` → `1.14.0`
- ✅ `README.md`: `1.11.0` → `1.14.0`
- ✅ …
> Fix: Synchronize version files to match git tag v1.14.0

- .github/workflows/claude-auto-approval.yml
**Issue**: After fixing the string matching issue, the workflow is still failing in the "Evaluate Claude AI Approval" step.
**Root Cause**: Debug logging code causing JavaScript error:
```javascript
// PROBLEMATIC CODE (Line 96)
comment.body.substring(comment.body.indexOf('FINAL VERDICT'), comment.body.indexOf('FINAL VERDICT') + 200)
```
**Problem**: If `indexOf('FINAL VERDICT')` returns `-1`, then `substring(-1, 199)` causes a JavaScript error.
```javascript
// OLD (error-prone)
comment.body.substring(comment.body.indexOf('FINAL VERDICT'), comment.body.indexOf('FINAL VERDICT') + 200)
// NEW (safe)
const verdictIndex = comment.body.indexOf('FINAL VERDICT');
if (verdictIndex !== -1) {
console.log('Comment excerpt: ' + comment.body.substring(verdictIndex, verdictIndex + 200));
} else { …
```
> 🔧 HOTFIX #2: Claude AI auto-approval debug logging error

- .github/scripts/file-change-analyzer.js
- docs/workflow-version-tag-fix.md
- scripts/get-ignore-patterns.sh
- scripts/verify-version-tag-fix.js
Resolves the critical issue where version tags were being created despite PRs containing only workflow file modifications that should be ignored by the versioning logic.
**Root Cause**: Bug in `.github/scripts/file-change-analyzer.js` pattern matching logic that prevented proper exclusion of `.github/` directory files.
**Impact**: Eliminates unnecessary version bumps and releases for internal workflow changes.
---
The issue was caused by a **pattern matching bug** in the `shouldIgnoreFile()` function:
```javascript
// BEFORE (Buggy)
const regex = new RegExp(`^${regexPattern}$`);
return regex.test(filePath);
```
**Problem**: Pattern `.github/` was converted to regex `^\.github/$` which only matched the exact string `.github/` and not files within that directory like …
> fix: resolve version tag changes for workflow file modifications

- .github/workflows/claude-auto-approval.yml
This PR fixes the **root cause** of why the Claude AI auto-approval system wasn't working: **incorrect authentication token configuration**.
- ✅ Claude AI successfully reviewed PRs and posted `FINAL VERDICT: APPROVED`
- ✅ Auto-approval workflow triggered correctly via `issue_comment` and `workflow_run`
- ✅ Workflow appeared to "succeed" with no errors in logs
- ❌ **BUT: No actual PR approvals appeared in GitHub UI**
- ❌ **@blazecommerce-claude-ai never approved any PRs**
The workflow was using the **default `GITHUB_TOKEN`** instead of the **`BOT_GITHUB_TOKEN` secret**:
**Before (Broken)**:
```yaml
uses: actions/github-script@v7
with:
script: |
await github.rest.pulls.createReview({...})  # Used default token
```
**After (Fixed)**:
```yaml
uses: actions/github-script@v7
with:
github-token: …
```
> 🔐 FIX: Claude AI Auto-Approval Authentication - Enable @blazecommerce-claude-ai Bot

- .github/workflows/tests.yml
- docs/php-test-workflow-fixes-comprehensive.md
- docs/php-workflow-troubleshooting-guide.md
- docs/pr374-comprehensive-fixes-summary.md
- docs/workflow-failure-analysis-pr374.md
- scripts/monitor-pr374-fixes.js
- scripts/monitor-workflow-execution.js
- scripts/validate-php-workflow-fixes.js
- tests/bootstrap.php
This PR implements comprehensive fixes for the failing PHP test workflows in GitHub Actions, addressing all identified issues from PR #337 and implementing robust error handling, retry mechanisms, and enhanced monitoring across all PHP and WordPress version combinations.
- ✅ **Upgraded to MySQL 8.0** with enhanced compatibility
- ✅ **Added native password authentication** for better connection stability
- ✅ **Enhanced health checks** with 30-second startup period and 5 retries
- ✅ **Improved connection verification** with multiple validation methods
- ✅ **Enhanced security configuration** with explicit plugin allowlists
- ✅ **Platform-specific PHP configuration** for matrix compatibility
- ✅ **Triple retry mechanism** with cache clearing between attempts
- ✅ **Increased timeout to 600 …
> feat: comprehensive PHP test workflow fixes for GitHub Actions pipeline

- .github/workflows/auto-version.yml
- .github/workflows/claude-auto-approval.yml
- .github/workflows/release.yml
- docs/blazecommerce-automation-bot-setup.md
- docs/github-app-implementation-guide.md
- docs/github-app-migration-guide.md
- package.json
- scripts/test-automation-bot.js
- scripts/test-github-app-auth.js
- scripts/test-release-workflow-auth.js
- scripts/test-token-auth.js
This PR implements a unified GitHub App approach that replaces separate authentication methods for both auto-approval and version bumping workflows, consolidating the `@blazecommerce-claude-ai` user functionality into a single, secure GitHub App.
**Single GitHub App can handle both functions** ✅
- Auto-approval of PRs (replacing `@blazecommerce-claude-ai`)
- Version bumping (enhancing current auto-version workflow)
- Unified identity and consistent behavior
- Enhanced security with granular permissions
- ✅ **Auto-Version Workflow**: Enhanced with GitHub App authentication
- ✅ **Auto-Approval Workflow**: Migrated from `BOT_GITHUB_TOKEN` to GitHub App
- ✅ **Unified Identity**: All automation now appears from "BlazeCommerce Automation Bot"
- ✅ **Fallback Support**: Maintains compatibility …
> feat: integrate BlazeCommerce Automation Bot for consolidated GitHub App authentication

- .github/workflows/auto-version.yml
- .github/workflows/claude-auto-approval.yml
- .github/workflows/claude-code-review.yml
- .github/workflows/claude-direct-approval.yml
- .github/workflows/claude.yml
- .github/workflows/release.yml
- .github/workflows/test-claude-approval.yml
- .github/workflows/test-claude-output-fix.yml
- .github/workflows/tests.yml
This PR updates all GitHub workflow display names to follow a consistent priority-based naming convention, improving organization and readability in the GitHub Actions UI while removing emojis for better compatibility.
| **Priority** | **Filename** | **New Display Name** | **Purpose** |
|--------------|--------------|---------------------|-------------|
| **1** | `claude-direct-approval.yml` | `Priority 1: Claude Direct Approval` | Highest priority - runs first |
| **2** | `claude-code-review.yml` | `Priority 2: Claude AI Code Review` | Depends on Priority 1 |
| **3** | `claude-approval-gate.yml` | `Priority 3: Claude AI Approval Gate` | Depends on Priority 2 |
| **4** | `auto-version.yml` | `Priority 4: Auto Version Bump` | Depends on Priority 3 |
| **5** | `release.yml` | `Priority 5: …
> feat: update GitHub workflow names to follow priority-based convention

- .github/scripts/file-change-analyzer.js
- .github/workflows/auto-version.yml
- docs/auto-version-workflow-fixes-comprehensive.md
- docs/auto-version-workflow-fixes-implementation-summary.md
- package.json
- scripts/get-ignore-patterns.sh
- scripts/test-file-change-analyzer.js
- scripts/validate-auto-version-fixes.js
This PR resolves critical issues in the BlazeCommerce WordPress plugin's automated versioning system where ignored files were incorrectly triggering version bumps and git tags were being created despite validation failures.
**Problem**: Ignored files like `.github/workflows/`, `docs/`, `scripts/`, etc. were incorrectly triggering version bumps.
**Root Cause**: 
- Directory patterns like `.github/` didn't properly match files like `.github/workflows/auto-version.yml`
- Comment lines from ignore patterns weren't filtered out
- Pattern matching logic was incomplete and had several edge cases
**Problem**: Git tags were being created even when validation steps failed in the workflow.
**Root Cause**: 
- Workflow steps lacked proper error handling with `success()` conditions
- No validation of …
> fix(automation): resolve auto-version workflow issues with file change detection and error handling

- .github/workflows/claude-approval-gate.yml
- package-lock.json
- package.json
- scripts/test-auto-approval-issue.js
- test-auto-approval-fix.md
This PR fixes the **root cause** of why auto-approvals were being skipped even when Claude AI posted "FINAL VERDICT: APPROVED" status.
- ✅ Claude AI successfully reviewed PRs and posted `FINAL VERDICT: APPROVED`
- ✅ Auto-approval workflow triggered correctly via `issue_comment` event
- ❌ **BUT: Workflow was SKIPPED due to `if` condition failure**
- ❌ **No actual PR approvals happened**
- **Status**: `completed`
- **Conclusion**: `skipped` ❌
- **Timeline**: 
- `19:37:02Z`: Claude posts "FINAL VERDICT: APPROVED"
- `19:37:05Z`: Auto-approval workflow triggers (3 seconds later)
- `19:37:06Z`: Workflow completes as **SKIPPED**
The workflow condition was too restrictive and failing validation:
**Before (Broken)**:
```yaml
if: |
github.event_name == 'workflow_dispatch' || 
(github.event_name == …
```
> 🔧 URGENT FIX: Auto-Approval Workflow Skipping Issue

- .github/workflows/release.yml
Resolves the "Unrecognized named-value: 'secrets'" error in `.github/workflows/release.yml` at line 395.
**Error Details:**
- **GitHub Actions Run**: https://github.com/blaze-commerce/blazecommerce-wp-plugin/actions/runs/16281552970
- **Location**: Line 395, Column 11 in `.github/workflows/release.yml`
- **Error Type**: "Unrecognized named-value: 'secrets'"
- **Expression**: `secrets.BC_GITHUB_APP_ID && secrets.BC_GITHUB_APP_PRIVATE_KEY`
GitHub Actions doesn't allow direct access to the `secrets` context in step-level `if` conditions. The secrets must first be exposed as environment variables, then referenced via the `env` context.
Applied the same fix pattern that was already successfully implemented in:
- Same file (lines 23 and 86) ✅
- `.github/workflows/auto-version.yml` (line 150) ✅ …
> fix(workflows): resolve secrets context error in release.yml line 395

- .github/workflows/claude-approval-gate.yml
Test PR #405 validation revealed a critical conditional logic issue preventing automatic `issue_comment` triggers from executing the `claude-approval-gate` job:
- **Manual triggers (`workflow_dispatch`)**: ✅ Working perfectly (validated in run 16285028954)
- **Automatic triggers (`issue_comment`)**: ❌ `claude-approval-gate` job **skipped** due to conditional logic failure (run 16284958880)
- **Impact**: Auto-approval system requires manual intervention instead of automatic execution
```yaml
if: |
github.event_name == 'workflow_dispatch' ||
(github.event_name == 'issue_comment' &&
contains(github.event.comment.body, 'FINAL VERDICT') &&
contains(github.event.comment.body, 'Claude AI PR Review Complete') &&
(github.event.comment.user.login == 'blazecommerce-automation-bot[bot]' || …
```
> fix: resolve automatic issue_comment trigger logic in Claude AI Approval Gate workflow

- .github/workflows/claude-approval-gate.yml
- docs/claude-comment-detection.md
The Claude AI Approval Gate workflow was failing to detect "FINAL VERDICT" in Claude's comments due to formatting sensitivity in the validation logic, preventing the automatic approval system from functioning reliably.
**Root Cause**: The current detection logic is case-sensitive and formatting-sensitive, causing it to miss Claude's "FINAL VERDICT" comments that contain HTML formatting, markdown, or different case variations.
- ❌ Approval gate workflow skips approval creation despite valid Claude verdicts
- ❌ Complete end-to-end automation fails due to detection false negatives
- ❌ Manual intervention required for legitimate APPROVED verdicts
- ❌ Production reliability compromised by rigid string matching
**Before (Rigid Detection)**:
```bash
if echo "${COMMENT_BODY}" | grep -q "FINAL …
```
> fix: implement format-agnostic Claude comment detection for FINAL VERDICT matching

- .github/workflows/claude-code-review.yml
The GitHub Actions workflow for Claude AI Code Review (`Priority 2: Claude AI Code Review`) was consistently failing with the following error:
```
API Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"'claude-3-5-sonnet-20241022' does not support thinking."}}
```
This error occurred during the execution of the `anthropics/claude-code-action@v0.0.32` step, preventing automated code reviews from completing successfully.
**Reference**: [Failing GitHub Actions run](https://github.com/blaze-commerce/blazecommerce-wp-plugin/actions/runs/16289054536/job/45994479942)
After investigation, the root cause was identified as an **incorrect model identifier** being used in the workflow configuration:
- ❌ **Problem**: The workflow was using `claude-3-5-sonnet-20241022` as the …
> fix(workflows): update Claude 3.5 Sonnet model identifier to resolve API errors

- .github/scripts/test-cost-optimization.js
- .github/workflows/claude-code-review.yml
- docs/claude-cost-optimization.md
The Claude Haiku model (`claude-3-haiku-20240307`) has been experiencing operational issues, causing inconsistent and unreliable AI code reviews. This PR addresses these issues by standardizing on Claude Sonnet 4 for all code reviews.
- **`.github/workflows/claude-code-review.yml`** - Removed intelligent model selection logic, always use Claude Sonnet 4
- **`.github/scripts/test-cost-optimization.js`** - Updated test scenarios and model selection function
- **`docs/claude-cost-optimization.md`** - Updated documentation to reflect consistent model usage
- ✅ **Removed intelligent model selection logic** - No more complex decision trees based on file types/sizes
- ✅ **Standardized on Claude Sonnet 4** - All reviews now use `claude-3-5-sonnet-20240620`
- ✅ **Simplified workflow logic** - …
> fix: replace Claude Haiku with Claude Sonnet 4 for consistent AI reviews

- .github/workflows/claude-code-review.yml
This PR adds comprehensive API validation to help diagnose the actual root cause of GitHub Actions failures in the Claude Code Review workflow, instead of making assumptions about emoji encoding issues.
The previous approach of replacing emojis was based on an assumption without confirming the actual error. This PR takes a proper diagnostic approach to identify the real issue.
- **Format Validation**: Checks if API key starts with `sk-ant-` prefix
- **Live API Test**: Makes actual API call to Anthropic before running Claude action
- **HTTP Status Analysis**: Detailed handling of different response codes:
- `200` ✅ Success
- `401` ❌ Invalid API key
- `403` 🚫 Insufficient permissions
- `429` ⏳ Rate limiting
- `5xx` 🔥 Server errors
- `000` 🌐 Network issues
- **Conditional Execution**: Claude …
> feat: add comprehensive Anthropic API validation for debugging GitHub Actions failures

- .github/workflows/claude-approval-gate.yml
- .github/workflows/claude-code-review.yml
Simplify the Claude AI auto-approval system to use a single, clear approval indicator: `PR_APPROVED_BY_BLAZE_BOT`.
- Changed approval status from `**Status**: APPROVED` to `**Status**: PR_APPROVED_BY_BLAZE_BOT`
- Updated status options to include `PR_APPROVED_BY_BLAZE_BOT | CONDITIONAL APPROVAL | BLOCKED`
- **Removed complex pattern matching** for "FINAL VERDICT", "final verdict", "finalverdict"
- **Removed status format checking** for "Status: APPROVED", "**Status**: APPROVED", etc.
- **Simplified to single condition**: Only looks for `PR_APPROVED_BY_BLAZE_BOT` string in comments
- **Removed "Claude AI PR Review Complete" requirement**
- **Streamlined bot detection** - removed unnecessary content checks
- Main approval detection logic
- Fallback approval detection logic  
- Validation …
> feat: simplify auto-approval to use PR_APPROVED_BY_BLAZE_BOT status

- app/BlazeWooless.php
This PR adds comprehensive version information utilities to the BlazeWooless plugin to improve debugging and support diagnostics.
- **Added `get_version_info()` method**: Returns comprehensive plugin version details including:
- Plugin version (from BLAZE_COMMERCE_VERSION constant)
- Plugin name
- Build timestamp
- PHP version
- WordPress version
- **Added `is_version_compatible()` method**: Checks version compatibility against minimum requirements
- **Enhanced diagnostics capabilities**: Useful for support and debugging scenarios
- Methods added to `app/BlazeWooless.php` main class
- Follows WordPress coding standards
- Includes proper PHPDoc documentation
- Version tagged as `@since 1.15.0` (expected after auto-version bump)
1. Merge this PR to trigger auto-version workflow
2. Version …
> feat: integrate version info utilities with plugin diagnostics for development

- app/BlazeWooless.php
This PR adds comprehensive logging and performance monitoring utilities to improve debugging capabilities and system optimization analysis.
- **Structured logging** with timestamp, level, and context
- **Conditional activation** - only works when `WP_DEBUG` is enabled
- **Context support** - accepts additional data for detailed debugging
- **WordPress integration** - writes to WordPress debug.log when available
- **Multiple log levels** - info, warning, error, debug
- **Execution time tracking** with microsecond precision
- **Memory usage monitoring** (current and peak)
- **Operation categorization** for performance analysis
- **Custom metrics support** for additional performance data
- **Automatic formatting** for easy log parsing
- Added to `app/BlazeWooless.php` main class for global …
> feat: integrate enhanced logging utilities for debugging and performance monitoring

- README.md
- blaze-wooless.php
This PR is designed to trigger the auto-version workflow and bump the version from **1.14.5** to **1.14.6**.
- **Enhanced debugging support**: Updated comment in `blaze-wooless.php` to improve developer experience
- **Updated README testing comment**: Modified testing comment to reflect patch version bump validation
✅ **Auto-Version Workflow Should:**
1. Detect the `fix:` conventional commit message
2. Determine this requires a **patch** version bump
3. Update version from `1.14.5` → `1.14.6` in:
- `package.json`
- `blaze-wooless.php` (header and constant)
- `README.md`
- `blocks/package.json`
4. Create git tag `v1.14.6`
5. Commit and push the version changes
1. **Merge this PR** to trigger the auto-version workflow
2. **Monitor the workflow** in GitHub Actions:
- Priority 4: Auto Version …
> feat: trigger patch auto-version bump for workflow testing

- .github/workflows/auto-version.yml
- README.md
This PR implements a comprehensive solution to resolve the **"GH013: Repository rule violations"** error by replacing the direct push approach with a robust PR creation and auto-merge system.
- ✅ **Multi-line string parsing**: Replaced problematic heredoc syntax with string concatenation
- ✅ **YAML boolean parsing**: Fixed 'on' key being interpreted as boolean True
- ✅ **Special character escaping**: Resolved conflicts with YAML parser
- ✅ **Workflow structure validation**: All required sections properly configured
```
✅ Workflow name
✅ Workflow triggers  
✅ Jobs section
✅ Push trigger
✅ Branch filters
✅ Job: wait-for-priority-3
✅ Job: feature-branch-info
✅ Job: version-bump
🎉 All YAML validation checks passed!
```
- Repository rulesets require **pull requests** for changes to main branch …
> feat: implement robust PR + auto-merge workflow for version bumps

- SECURITY-AUDIT-REPORT.md
This PR **replaces the security portion of problematic PR #457** with a **focused security assessment** for the blazecommerce-wp-plugin repository.
- **ClickUp API Token**: `pk_54603746_[REDACTED]`
- **Figma Token**: `figd_[REDACTED]`
- **Vercel Token**: `[REDACTED]`
- **Vercel Team ID**: `team_[REDACTED]`
- **Typesense Key**: `[REDACTED]`
- ✅ **Working Directory**: All tracked files (excluding .env.local, node_modules, vendor)
- ✅ **Git History**: Complete repository history across all branches
- ✅ **All Commits**: Every commit in repository timeline
| Security Check | Status | Result |
|----------------|--------|--------|
| **Working Directory Scan** | ✅ CLEAN | 0 credentials found |
| **Git History Scan** | ✅ CLEAN | 0 credentials found |
| **Overall Security Status** | ✅ EXCELLENT | …
> security: remove exposed API credentials from git history

- .augment/rules/workflow-optimization-checklist.yaml
- .augment/rules/workflow-optimization-summary.yaml
This PR **replaces the problematic PR #457** with a **clean, focused change** that converts Augment rule files from `.md` to `.yaml` format with proper frontmatter structure.
- ✅ **Convert workflow-optimization-checklist.md to .yaml** with proper YAML frontmatter
- ✅ **Convert workflow-optimization-summary.md to .yaml** with proper YAML frontmatter
- ✅ **Add required frontmatter fields**: type, priority, scope, description
- ✅ **Maintain all original content** while standardizing format
- ✅ **Remove original .md files** after successful conversion verification
```yaml
---
type: "recommended"  # workflow optimization guidelines
priority: 3          # documentation level
scope: "blazecommerce_wp_plugin"  # repository-specific
description: "Descriptive summary of rule purpose"
---
```
| …
> docs: convert augment rules from .md to .yaml format with proper frontmatter
